### ISSUE TITLE
导入小程序报错

### ISSUE THREAD

**Issue by lewiswon** [maxim-top/maxim-miniprogram#1]
按照文档步骤操作后，导入小程序开发者工具报错。
VM9:1 pages/account/login/index.json: ["usingComponents"]["snav"]: "../components/snav/index" not found

**Comment by ericliang** [comment]
这个报错应该是因为你没有按照 NPM，请按照 README 说明做好开发前准备工作：

```
npm init
npm install --production
npm install -S --production ericliang/protobufjs.wechat
```

然后在小程序开发者工具中选择「构建 NPM」

具体可参见：https://github.com/maxim-top/maxim-miniprogram#开发准备
