### ISSUE TITLE
替换 appid 之后登录不了无法正常运行

### ISSUE THREAD

**Issue by Spencer17x** [maxim-top/maxim-miniprogram#3]
替换了 appid 后报错：
![image](https://user-images.githubusercontent.com/32794413/130901889-fe075449-1859-4e3c-86d9-ef5fd497340e.png)

且无法正常登录。

文档注明：打开文件 app.js, 修改变量 USER_CONFIG_APPID 为你的应用AppID，此 AppID 为在美信拓扑后台创建应用后获取。
但是 app.js 没有该字段，只有 appid

**Comment by ericliang** [comment]
Demo 已完成相关修改 https://github.com/maxim-top/maxim-miniprogram/commit/9b6f7a6ea628e09269dc03fa0f2bf649a88a9897 ，感谢 @Spencer17x 建议。
