### ISSUE TITLE
npm install --production 报错

### ISSUE THREAD

**Issue by Spencer17x** [maxim-top/maxim-miniprogram#4]
报错如下：
![image](https://user-images.githubusercontent.com/32794413/131303575-c5b2714f-a807-4895-a379-998a978a7603.png)

node 版本：v12.22.1
npm 版本：7.20.6

**Comment by Spencer17x** [comment]
用 yarn 可以正常运行

**Comment by ericliang** [comment]
这个看起来像是新版 npm 的检查更严格了，可以试下：

`npm install --legacy-peer-deps`  

也可以设置下一直接受：

`npm config set legacy-peer-deps true`

回头我们看下，是否提高 extract-text-webpack-plugin 的版本。

**Comment by Spencer17x** [comment]
可以考虑替换为 yarn 或者 pnpm，并且上传对应的 lock 文件，不然会有差异化的问题，其次包管理工具个人建议是 pnpm > yarn > npm。

**Comment by ericliang** [comment]
> 可以考虑替换为 yarn 或者 pnpm，并且上传对应的 lock 文件，不然会有差异化的问题，其次包管理工具个人建议是 pnpm > yarn > npm。

感谢建议，不过我没记错的话，微信小程序开发者工具好像只支持 npm 。

**Comment by Spencer17x** [comment]
他们都是 npm 的包管理工具，运行之后安装的也都是 npm 包。微信小程序开发者工具支持 npm，并不是说只支持 npm 包管理工具。

**Comment by Spencer17x** [comment]
有一点我纠正下，就是小程序的话不适用 pnpm，和 pnpm 实现原理有关，pnpm 用的是软链的方式，所以小程序的话还是 yarn > npm 吧

**Comment by ericliang** [comment]
这个要考虑下。因为现在小程序那个开发 IDE 里，只有一个菜单是「构建 npm」，所以不确定跟 yarn 的配合怎么样。你有测试过吗？

另外，感觉还是有一部分开发者会只懂 npm 不太熟 yarn ？

**Comment by Spencer17x** [comment]
没啥多大区别，只是命令的不同，然后 yarn 少了很多 npm 的坑。而且基本上都用了 yarn/pnpm 了。当然，这也只是一个建议而已，小程序用 yarn 是没问题，npm 构建只是意味着构建 npm 包而已。当然，这也只是个建议而已。

**Comment by ericliang** [comment]
> 没啥多大区别，只是命令的不同，然后 yarn 少了很多 npm 的坑。而且基本上都用了 yarn/pnpm 了。当然，这也只是一个建议而已，小程序用 yarn 是没问题，npm 构建只是意味着构建 npm 包而已。当然，这也只是个建议而已。

感谢建议，我们其他 web 工程都是 yarn 了，就是这一个还是在文档里建议 npm。再观察一段时间，没问题的话可以切换倒是。

这个 issue 先关闭掉啦。
