### ISSUE TITLE
uploadVoice 修改文件名之后 wx.uploadFile 返回  http code 400 bad request

### ISSUE THREAD

**Issue by spencer17x** [maxim-top/maxim-miniprogram#6]
复现步骤：群组聊天 => 发送语音 => 调用到 uploadVoice 函数的时候 name 字段由 'file' 改为其他字符串的时候报错

![image](https://user-images.githubusercontent.com/32794413/133032353-a500fcb9-5ce6-4ff0-9ace-4ffeb8d70feb.png)

cURL:
curl 'https://chat-file-chatroom-1-3.oss-cn-beijing.aliyuncs.com/' \
  -X 'post' \
  -H 'Content-Type: multipart/form-data' \
  -H 'access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2NjYxODgwMjU2NTI4IiwiY2x1c3RlciI6Mywicm9sZSI6MCwiZXhwIjoxNjMyMTE3OTkyLCJpYXQiOjE2MzE1MTMxOTJ9.I3zwrgwLJZIJms6rrnYeppGlLYm4yMl1TmZnB2SEBg7lQQBg2ZMF2KxwZDOS6K96-s3hczsW7ZHcI2Mn-Y0Zwg' \
  -H 'app_id: welovemaxim' \
  -H 'Referer: https://servicewechat.com/wxc78052ce50ca2357/devtools/page-frame.html' \
  -H 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1 wechatdevtools/1.05.2107221 MicroMessenger/8.0.5 Language/zh_CN webview/' \
  --compressed

**Comment by theorix** [comment]
这个字段只可以设置为'file', 这个是OSS限制的， 可以参考下面文档的步骤4： https://help.aliyun.com/document_detail/92883.html

**Comment by spencer17x** [comment]
所以这个name不是文件名的含义吗？如果是文件名的话，不是导致覆盖问题吗？

**Comment by theorix** [comment]
不是文件名，不会覆盖，传到oss的还有参数key, 应该靠key的值来决定覆盖的。可以看下这个： https://developers.weixin.qq.com/community/develop/doc/0000a85fc90a20c8fa4afc53656c00
